version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  build_for_me_precious:
    jobs:
      - build